# Generated by Django 3.2.22 on 2023-11-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_post_author_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_profile',
        ),
    ]
