# Generated by Django 3.2.22 on 2023-11-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_remove_post_author_profile'),
        ('user', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
